services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=mydatabase'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#    ports:
#      - '3306'
  postgres:
    image: 'postgres:16.4'
    container_name: postgres_football_records
    networks:
      - football_api_postgres
    environment:
      - 'POSTGRES_DB=OrdersDB'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=ordersUser'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data-football-matches:/var/lib/postgresql/data

networks:
  football_api_postgres:

volumes:
  postgres-data-football-matches:
